### ISSUE TITLE
Connecting thru unix sockets?

### ISSUE THREAD

**Issue by pyryson** [3rd-Eden/memcached#176]
On the server where I host my node.js -project, it't has memcache installed out of the box. My problem is that only way to connect that is to use Unix socket -connection. I'd love to see that it'd be possible to connect node-memcached to memcache-server using Unix sockets.

 Or is it already possible?

**Comment by akshayajddn** [comment]
Hi, my machine is running a memcached server on unix socket.
/var/run/memcached/memcached.sock.
But, my application is not able to connect to it.
The code is as follows:-
var cacheAddr = process.env.CACHE_ADDR;
 var servers = [];
 servers.push(cacheAddr);      
  var memcached = new Memcached(servers, {});
Here cacheAddr is /var/run/memcached/memcached.sock

What am I doing wrong?
