### ISSUE TITLE
TypeError: Cannot call method 'replace' of undefined

### ISSUE THREAD

**Issue by tobsn** [3rd-Eden/memcached#223]
```
..app/node_modules/memcached/lib/utils.js:152
  return value.replace(/(\r|\n)/g, '\\$1');
               ^
TypeError: Cannot call method 'replace' of undefined
```

just freshly installed.

never mind, fixed it - old code...

**Comment by wiseflat** [comment]
Hi tobsn,
I have the same problem.
I don't know what happened because it worked during a couple of weeks.
What did you do ?
I updated the source code (npm install 3rd-Eden/node-memcached)
Same result ...
