### ISSUE TITLE
AsynAndSyn

### ISSUE THREAD

**Issue by GanLuo96214** [3rd-Eden/memcached#262]
all method was asyn?
if not whitch option can change asyn method to syn.

**Comment by ronkorving** [comment]
Nothing can be synchronous, as there is no such thing as synchronous network operations in Node as far as I know.

**Comment by GanLuo96214** [comment]
Just hard to make the code clean,thanks.
thanks u for doing about on the github.

**Comment by ronkorving** [comment]
I advise you to try to stop thinking about writing all code synchronously. It's not right for Node. But look into Promises, and the "async" and "co" modules on NPM. They provide different solutions to the asynchronous callback challenge. You may like some of them.

**Comment by GanLuo96214** [comment]
thanks.I got.Can u see this: https://github.com/3rd-Eden/memcached/issues/263

**Comment by ronkorving** [comment]
Yes :)
