### ISSUE TITLE
Garbled In The Memcached

### ISSUE THREAD

**Issue by GanLuo96214** [3rd-Eden/memcached#263]
i used the php memcached saved something(include chinese).when i console.log what i saved like this:
-- Begin
��?a:1000:{i:0;a:7:{s:2:"id";s:4:"3584@
5:"mp_�6:"6`@8:"store�1:"1�memberI`I 2249952�sendtime@10 439790750` �@!erAvatar@63:"http://static.weiwubao.com/download/image/20140512/15301735.jp �F7@�stest";}i:1�
                   �84`����2�
                              �585A'���3�
                                          �84b����4�
                                                     �58c����5�
                                                                �84d����6�
                                                                           �587���7�
     �843���8�
               �588���9�
                         �84�����9���1�����1��9���1�����1��9���1�����1��9���1�����1��9���1�����2��9���2�������2�����2��5���2�����2������������2��5���2�����2��5�60���4��6���4�����4��6���4�����4��6���4�����4��6���4�����4��6���5�����5�����5��1���5�����5��1���5�����5��1���5�����5��1���5�����6��1���6��7���6�����6��7���6�����6��7���6�����6��7���6�����6��7���7�����7�����7��2���7�����7��2���7�����7��2���7�����7��2���7�����8��2���8��8���8�����8��8���8�����8��8���8�����8��8���8�����8�����8�9�����9�����9��3���9�����9��3���9�����9��3���9�����9��3���9�����10�3��10����90���10����90���10����90���10����0�10�	���9
11�	��
9���91��D6���O��D9���91��D6���O��D9���91��D6���O��D9���913����O9���9 1��D!���O!1��D"9���9"1��D#���O#1��D$9���9$1��D%���O%1��D&9���9&1��D'���O'9���9(1��D)���O)1��D*9���9*1��D+���O+1��D,9���9,1��D-���O-1��D.9���9.1��D/���O/1��D09���901��D1���O11��D29���921��D3���O31��D49���941��D5���O51��D69���961��D7���O71��D89���981��D9���O91��D:9���9:1��D;���O;1��D<9���9<1��D=���O=1��D>9���9>1��D?���O?1��D@9���9@1��DA���OA1��DB9���9B1��DC���OC1��DD9���9D1��DE���OE1��DF9���9F1��DG���OG1��DH9���9H1��DI���OI1��DJ9���9J1��DK���OK1��DL9���9L1��DM���OM1��DN9���9N1��DO���OO1��DP9���9P1��DQ���OQ1��DR9���9R1��DS���OS1��DT9���9T1��DU���OU1��DV9���9V1��DW���OW1��DX9���9X18��0P���OY18��2���9Y��D[���O[1��D\9���9Y��D]���O]1��D^9���9Y��D_���O_1��D`9���9Y��Da���Oa1��Db9���9Y��Dc���Oc1��Dd9���9Y2��Dd���Oe2��Dd9���9Y2��Dd���Og2��Dd9���9Y2��Dd���Oi2��Dd9���9Y2��Dd���Ok2��Dd9���9Y20����Om20����9Y2��Dd���Oo2��Dd9���9Y2��Dd���Oo2��Dd9���9Y2��Dd���Oo2��Dd9���9Y2��Dd���Oo2��Dd9���9Y2��Dd���Oo2��Dd9���9Y2��Dd���Oo2��Dd���9Y2��Dd���Oo2��Dd���9Y2��Dd���Oo2��Dd���9Y2��Dd���Oo2��Dd���9Y2��Dd���Oo2��Dd���9Y2��Dd���Oo2��Dd���9Y2��Dd7���Oo2��Dd���9Y2��Dd7���Oo2��Dd���9Y2��Dd7���Oo2��Dd���9Y2��Dd7���Oo2��Dd���9Y2��Dd7���Oo2��Dd���9Y2��Dd7���Oo2��Dd���9Y2��Dd7���Oo2��Dd���9Y2��Dd7���Oo2��Dd���9Y2��Dd7���Oo2��Dd���9Y2��Dd7���Oo2��Dd���9Y2��Dd7���Oo2��Dd7���Nn2��Dd7���Mm2��Dd7���Ll2��Dd7���Kk2��Dd7���Jj2��Dd7���Ii2��Dd7���Hh2��Dd7���Gg2��Dd7���Ff2��Dd7���Ee2��Dd7���Dd2��Dd7���Cc2��Dd7���Bb2��Dd7���Aa2��Dd7���@`2��Dd7���?_2��Dd7���>^2��Dd7���=]2��Dd7���<\2��Dd7���;[2��Dd7���:Z2��Dd7���9Y2��Dd7���8X2��v�7���2R��Dd7���1Q��Dd7���0P��Dd7���/O��Dd7���.N��Dd7���-M��Dd7���,L��Dd7���+K��Dd7���*J��Dd7���)I��Dd7���(H��Dd7���'G��Dd7���&F��Dd7���%E��Dd7���$D��Dd7���#C��Dd7���"B��Dd7���!A��Dd7��� @3��Dd7���?3��Dd7���>3��Dd7���=3��Dd7���<3��Dd7���;3��Dd7���:3��Dd7���93��Dd7���83��Dd7���p�3��Dd7���o�3��Dd7���n�3��Dd7���m�3��Dd7���l�3��Dd7���k�3��Dd7���j�3��Dd7���i�3��Dd7���h�3��Dd7���g�3��Dd7���f�3��Dd7���e�3��Dd7���d�3��Dd7���c�3��Dd7���b�3��Dd7���a�3��Dd7���`�3��Dd7���_3��Dd7���^~3��Dd7���]}3��Dd7���\|3��Dd7���[{3��Dd7���Zz3��Dd7���Yy3��Dd���Xx3��Dd7���Ww3��Dd���Vv3��Dd7���Uu3��Dd���Tt3��Dd7���Ss3��Dd���Rr3��Dd7���Qq3��Dd���Pp3��Dd7���Oo3��Dd8���Nn3��Dd8���Mm3��Dd8���Ll3��Dd8���Kk3��Dd8���Jj3��Dd8���Ii3��Dd8���Hh3��Dd8���Gg3��Dd8���Ff3��Dd8���Ee3��Dd8���Dd3��Dd5���83��Dd8���Ee!�;a:7:{s:2:"id";s:4:B�����3��Dd8���Ff3��Dd5���:��Dd8���Gg3��Dd5���;��Dd8���Hh3��Dd5���<��Dd8���Ii3��Dd5���=��Dd8���Jj3��Dd5���>��Dd8���Kk3��Dd5���?��Dd8���Ll3��Dd5��� @��Dd8���Mm3��Dd5���!A��Dd8���Nn3��Dd5���"B��Dd8���Oo3��Dd5���#C��Dd8���Pp3���&F��Dd8���Ss3��Dd5���'G��Dd8���Tt3��Dd5���(H��Dd8���Uu3��Dd5���)I��Dd8���Vv3��Dd5���*J��Dd8���Ww3��Dd5���+K��Dd8���Xx3��Dd5���,L��Dd8���Yy3��Dd5���-M��Dd8���Zz3��Dd5���.N��Dd8���[{3��Dd5���/O4��Dd8���\|4��Dd5���0P4��Dd8���]}4��Dd5���1Q4��Dd8���^~4��Dd5���2R4��Dd8���_4��Dd5���3S4��Dd8���`�4��Dd5���4T4��Dd8���a�4��Dd0�d��X�12:"senderAvatar";s:63:"http://static.weiwubao.com/download/image/201&�12/154:"test";}A2�7:"mess #@
                     3�d�t3�
                              0�d�t4�
�< �C-5#;p_��S6:"6`@8#�tore�1:"1�memberI�� 2249���
�d�t7�c�10 342�9 k9@<�n6�
���0�d�s��Dd&D�����Dd0�d�t�	�d�t�	8���	�d�t�	i����	5���	��20�d�t����	���Dd0�d�t��t���Dd0�d�Mm�t�	�d�z��t�	��
��Dd3�d�{��t�	��
��Dd3�d�|��s��Dd0�d�Pp�t�	�d�}��t��d�Qq�t�	�d�~��t��d�Rr�t�	���Dd0�d�Ss�t��d����t�	�d�Tt�s��Dd3�d����t��d�Uu�t�	����Dd0�d�Vv�t�	����Dd0�d�Ww�m�m(��Dd3�d����t��d�Xx�t�	�d����t�	����Dd3�d����s��Dd0�d�1�d�_�t�d�^~�s����Dd1�d�`��t�d����t�����Dd1�d�a��t��      �d�Qq�t�	����Dd3�d�Qq�t�	��
���3�d�Qq�t��d�g��t�1�d����Dd1�d�g��t���Dd1�d����Dd1�d�g��t�	�d�Qq�t��d�g��t�	�d�Qq�t��d�g��r5��Dd3���9Y5��Dd1�d�g��t�	���9Y5��Dd1�d�g��t�	���9Y5��Dd1�d�g��t�	��5��Dd1�d�g��t�	��5��Dd1�d�g��s��Dd3���9Y5��Dd1�d�g��t�	��5��Dd1�d�g��t�	��5��Dd1�d�g��t�	���9Y5��Dd1�d�g��t�	���9Y5��Dd1�d�g��s��Dd���9Y5��Dd1�d�g��t�	���9Y5��Dd1���Oo5��Dd���9Y5��Dd1���Oo5��Dd���9Y5��Dd1���Oo5��Dd���9Y5��Dd1���Oo5��Dd���9Y5��Dd1���Oo5��Dd���9Y5��Dd1���Oo5��Dd���9Y5��Dd1���Oo5��Dd���9Y5��Dd1���Oo5��Dd���9Y53�(���Oo5��Dd���9Y5��Dd1���Oo5��Dd���9Y5��Dd1���Oo5��Dd���9Y5��Dd1���Oo5��Dd���9Y5��Dd1���Oo5��Dd���9Y5��Dd1���Oo5��Dd���9Y5��Dd1���Oo5��Dd���9Y5��Dd1���Oo5��Dd���9Y5��Dd1���Oo5��Dd4���9Y5��Dd1���Oo5��Dd4���9Y5��Dd1���Oo5��Dd4���9Y5��Dd1���Oo5��Dd4���9Y5��Dd1���Oo5��Dd4���9Y5��Dd1��
                                          ����-M5��Dd4���9Y5��Dd���Oo5��Dd4���9Y5��Dd���Oo5��Dd4���9Y5��Dd���Oo5��Dd4���9Y5��Dd���Oo5��Dd4���9Y5��Dd���Oo5��Dd4���9Y5��Dd���Oo5��Dd4���9Y5��Dd���Oo5��Dd4���9Y5��Dd���Oo5��Dd4���9Y5��Dd���Oo5��Dd4���9Y5��Dd���Oo5��Dd4���9Y5��Dd���Oo5��Dd4���9Y8��2���Oo5��Dd4���9Y��Dd���Oo5��Dd4���9Y��Dd���Oo5��Dd4���9Y��Dd���Oo5��Dd4���9Y��Dd���Oo5��Dd4���9Y��Dd���Oo6��Dd4���9Y6��Dd���Oo6��Dd4���9Y6��Dd���Oo6��Dd4���9Y6��Dd���Oo6��Dd4���9Y6��Dd���Oo6��Dd4���9Y6��Dd���Oo6��Dd4���9Y6��Dd���Oo6��Dd4���9Y6��Dd���Oo6��Dd4���9Y6��Dd���Oo6��Dd4���9Y6��Dd���Oo6��Dd4���9Y6��Dd���Oo6��Dd4���9Y6��Dd���Oo6��Dd4���9Y6��Dd���Oo6��Dd4���9Y6��Dd���Oo6��Dd4���9Y6��Dd���Oo6��Dd4���9Y6��Dd���Oo6��Dd4���9Y6��Dd���Oo6��Dd4���9Y6��Dd���Oo6��Dd4���9Y6��Dd���Oo6��Dd4���9Y6��Dd���Oo6��Dd4���9Y6��Dd���Oo6��Dd4���9Y6��Dd���Oo6��Dd4���9Y6��Dd���Oo6��Dd4���9Y6��Dd���Oo6��Dd4���9Y6��Dd���Oo6��Dd4���9Y6��Dd���Oo6��Dd4���9Y6��Dd���Oo6��Dd4���9Y6��Dd���Oo6��Dd4���9Y6��Dd���Oo6��Dd���9Y6��Dd���Oo6��Dd���9Y6��Dd���Oo6��Dd���9Y6��Dd���Oo6��Dd���9Y6��Dd���Oo6��Dd���9Y6��Dd���Oo6��Dd���9Y6��Dd2���Oo6��Dd���9Y6��Dd2���Oo6��Dd���9Y6��Dd2���Oo6��Dd���9Y6��Dd2���Oo6��Dd���9Y6��Dd2���Oo6��Dd�����2���Oo6��Dd���9Y6��Dd2���Oo6��Dd���9Y6��Dd2���Oo6��Dd���9Y6��Dd2���Oo6��Dd���9Y��Dd2���Oo6��Dd���9Y��Dd2���Oo6��Dd���9Y��Dd2���Oo6��Dd���9Y��Dd2���Oo6��Dd���9Y��Dd2���Oo6��Dd���9Y��Dd2���Oo7��Dd���9Y7��Dd2���Oo7��Dd���9Y7��Dd2���Oo7��Dd���9Y7��Dd2���Oo7��Dd���9Y7��Dd2���Oo7��Dd���9Y7��Dd2���Oo7��Dd���9Y7��Dd2���Oo7��Dd���9Y7��Dd2���Oo7��Dd���9Y7��Dd2���Oo7��Dd���9Y7��Dd2���Oo7��Dd���9Y7��Dd2���Oo7��Dd���9Y7��Dd2���Oo7��Dd���9Y7��Dd2���Oo7��Dd���9Y7��Dd2���Oo7��Dd���9Y7��Dd2���Oo7��Dd���9Y7��Dd2���Oo7��Dd���9Y7��Dd2���Oo7��Dd���9Y7��Dd2���Oo7��Dd���9Y7��Dd2���Oo7��Dd���9Y7��Dd2���Oo7��Dd���9Y7��Dd2���Oo7��Dd���9Y7��Dd2���Oo7��Dd���9Y7��Dd2���Oo7��Dd���9Y7��Dd2���Oo7��Dd���9Y7��Dd2���Oo7��Dd���9Y7��Dd2���Oo7��Dd���9Y7��Dd2���Oo7��Dd���9Y7��Dd2���Oo7��Dd���9Y7��Dd2���Oo7��Dd5���9Y7��Dd2���Oo7��Dd5���9Y7��Dd2���Oo7��Dd5���9Y7��Dd2���Oo7��Dd5���9Y7��Dd2���Oo7��Dd5���9Y7��Dd2���Oo7��Dd5���9Y7��Dd���Oo7��Dd5���9Y7��Dd���Oo7��Dd5���9Y7��Dd���Oo7��Dd5���9Y7��Dd���Oo7��Dd5���9Y7��Dd���Oo7��Dd5���9Y7��Dd���Oo7��Dd5���9Y7��Dd���Oo7��Dd5���9Y7��Dd���Oo7��Dd5���9Y7��Dd���Oo7��Dd5���9Y7��Dd���Oo7��Dd5���9Y7��Dd���Oo7��Dd5���9Y��Dd���Oo7��Dd5���9Y��Dd���Oo7��Dd5���9Y��Dd���Oo7��Dd5���9Y��Dd���Oo7��Dd5���9Y��Dd���Oo7��Dd5���9Y��Dd���Oo8��Dd5���9Y8��Dd���Oo8��Dd5���9Y8��Dd���Oo8��Dd5���9Y8��Dd���Oo8��Dd5���9Y8��Dd���Oo8��Dd5���9Y8��Dd���Oo8��Dd5���9Y8��Dd���Oo8��Dd5���9Y8��Dd���Oo8��Dd5���9Y8��Dd���Oo8��Dd5���9Y8��Dd���Oo818;a:7:{s:2:"id";s:4:B1@
���2���Oo8��Dd5���9Y8��Dd���Oo8��Dd5���9Y8��Dd���Oo8��Dd5���9Y8��Dd���Oo8��Dd5���v�5���9Y8��Dd���Oo8��Dd5���9Y8��Dd���Oo8��Dd5���9Y8��Dd���Oo8��Dd5���9Y8��Dd���Oo8��Dd5���9Y8��Dd���Oo8��Dd5���9Y8��Dd���Oo8��Dd5���9Y8��Dd���Oo8��Dd5���9Y8��Dd���Oo8��Dd5���9Y8��Dd���Oo8��Dd5���9Y8��Dd���Oo8��Dd5���9Y8��Dd���Oo8��Dd548���"��Dd���Oo8��Dd5���9Y8��Dd���Oo8��Dd���9Y8��Dd���Oo8��Dd���9Y8��Dd���Oo8��Dd���9Y8��Dd���Oo8��Dd���9Y8��Dd���Oo8��Dd���9Y8��Dd���Oo8��Dd3���Nn8��Dd3���Mm8��Dd3���Ll8��Dd3���Kk8��Dd3���Jj8��Dd3���Ii8��Dd3���Hh8��Dd3���Gg8��Dd3���Ff8��Dd3���Ee8��Dd3���Dd8��Dd3���Cc8��Dd3���Bb8��Dd3���Aa8��Dd0���Aa8��Dd3���Aa8��Dd0���Aa8��Dd3���Aa8��Dd0���Aa8��Dd3���Aa8��Dd0���Aa8��Dd3���Aa8��Dd0���Aa8��Dd3���Aa8��Dd0���Aa8��Dd3���Aa8��Dd0���Aa8��Dd3���Aa8��Dd0���Aa8��Dd3���Aa8��Dd0���Aa��Dd3���Aa��Dd0���Aa��Dd3���Aa9��Dd0���Aa9��Dd3���Aa9��Dd0���Aa9��Dd3���Aa9��Dd0���Aa9��Dd3���Aa9��Dd0���Aa9��Dd3���Aa90�
                                    �:Z28�e��12:"senderAvatar";s:63:"http://static4:"test";}A�m/download/image/20140512/15301735.jpg@F7:"mess #@
                    �:Z!7@*�_�;[�r1�
                                    �0P!`����
                                             ���!9��2�
�Dd!�d�?_�s4�2��5�3��6�4��7�5���      �e             �>^28�ebn�m�
                                          �s�	�e
�Dd!6��e�Jjbn�m �                                 �r�
�Dd"��am��     3�
�Dd"a�����e�Bb�s�
�Dd"��
�Dd"�����bdp�m ���
�Dd"��
�Dd"��e�Bbdp��
�Dd"��
�Dd"a���e�Bb�r�
�Dd"��
�Dd26�e�Ccdp�m
�Dd"��
�Dd"���
�Dd"����
�Dd"��
�Dd"��e�:Zdp��
�Dd"��
�Dd"a����
�Dd"��
�Dd26�e�Mmdp�m
�Dd"��
�Dd"���
�Dd"����
�Dd"��
�Dd"��e�:Zdp��
�Dd"��
�Dd"�����:Z;
-- End
it means shout I change what i saved in memcached?

**Comment by GanLuo96214** [comment]
it's doesn't matter to change what i save in memcached by use php.

**Comment by 3rd-Eden** [comment]
I'm assuming that your PHP driver is encoding the data to save space a you're restricted to 1mb for values. This encoding probably not supported by the driver.

**Comment by GanLuo96214** [comment]
thanks,I trun compress off. the OPT_COMPRESSION this option is open as default.Would you will support the compressed data when use get method it and decompress it.
