### ISSUE TITLE
Using HashRing.createRange throws exception

### ISSUE THREAD

**Issue by danbatsb** [3rd-Eden/memcached#278]
The following line, within the memcached.command function, fails as there is no function called createRange on the HashRing object.

`redundancy = this.HashRing.createRange(query.key, (this.redundancy + 1), true);`

Looks like it should be calling `this.HashRing.range` and works fine when I changed it locally and tried it out.

Thanks

**Comment by mapleeit** [comment]
Fixed

**Comment by rauno56** [comment]
The fix is still unpublished.
