### ISSUE TITLE
Incorrect documentation

### ISSUE THREAD

**Issue by kcarlson** [3rd-Eden/memcached#279]
The `reconnected` event should be `reconnect` in the [Events](https://github.com/3rd-Eden/memcached#events-1) readme subsection

**Comment by ronkorving** [comment]
Indeed. The documentation is wrong on this one. The code [emits "reconnect"](https://github.com/3rd-Eden/memcached/blob/7b0439db64e2737087eacfb01358ecd80084bd4d/lib/memcached.js#L403). Mind making a pull request to fix this?

**Comment by ronkorving** [comment]
Fixed in #280
