### ISSUE TITLE
expired event

### ISSUE THREAD

**Issue by roccomuso** [3rd-Eden/memcached#287]
Is there available an event to catch when some key TTL time is reached and the key expires?

Like:

``` javascript
memcached.on( "del", function( key, value ){
    // ... do something ...   
});
```

**Comment by ronkorving** [comment]
No, afaik Memcached does not send notifications of any sort over the wire.

**Comment by roccomuso** [comment]
wouldn't be this a nice feature?
Redis got it, I guess.

**Comment by ronkorving** [comment]
Sure it would, but it doesn't seem compatible with the memcache protocol which afaik is always a client request based communication. In any case, this repo is not the Memcache repo of course, it's merely a client. Discussion on protocol and DB features don't belong here, but in the Memcache community (this repo is not officially affiliated). Given the age and stability of Memcached though, I seriously would not count on feature requests like this landing.
