### ISSUE TITLE
enable/disable

### ISSUE THREAD

**Issue by danikaze** [3rd-Eden/memcached#291]
I was just thinking it would be nice to have  a setting to test the same code with/without the usage of cache.
That is, if the `memcache.enabled = false` all the calls should be bypassed.

It would need a small wrapper to the calls, but an example of the spec for, let's say, `get()`/`set()` should be like this

```javascript
memcached.get = function(key, callback) {
    if(!enabled) {
        callback('ENOTENABLED'); // return an error when it's not enabled? or alternative spec.
        return;
    }
    
    // original code from here
    // ...
});
```

```javascript
memcached.set = function(key, callback) {
    if(!enabled) {
        // just bypass without error, but nothing cached (or alternative spec.)
        callback(null, true); 
        return;
    }
    
    // original code from here
    // ...
});
```

**Comment by mapleeit** [comment]
Can not figure out the purpose of adding this config for me. 
There are several years since opening this issue. So close it for now. Be free to reopen it if you have other ideas.
