### ISSUE TITLE
what's the reason for escaping the value?

### ISSUE THREAD

**Issue by jchip** [3rd-Eden/memcached#304]
Why is escaping the value done here https://github.com/3rd-Eden/memcached/blob/master/lib/memcached.js#L934 necessary?

**Comment by 3rd-Eden** [comment]
https://github.com/3rd-Eden/memcached/commit/e1faeebabb789594ee0d3268fe39efea5949c69c

**Comment by jchip** [comment]
OK, thanks.  Just want to point out that memcached server can handle any data:

```
$ telnet 10.1.1.1 11211
Trying 10.1.1.1...
Connected to 10.1.1.1.
Escape character is '^]'.
set foo 0 0 31
VALUE abc
END 20
set s
get

STORED
get foo
VALUE foo 0 31
VALUE abc
END 20
set s
get

END
^]
telnet> ^C
```
