### ISSUE TITLE
Connecting to couchbase?

### ISSUE THREAD

**Issue by kbjr** [3rd-Eden/memcached#306]
I am attempting to use a Couchbase memcached to test some code in development, but I can't seem to connect to it. I keep getting the same error

```
server=127.0.0.1:11211, tokens=[11211, 127.0.0.1], messages=[unauthorized, null bucket], failures=5, totalFailures=0
```

Is there some specific way I have to configure this to connect to the memcached bucket?

**Comment by ronkorving** [comment]
You're probably better off using https://www.npmjs.com/package/couchbase

**Comment by kbjr** [comment]
@ronkorving The issue with that is that we are actually using memcached in real environments, I just wanted to get something simple up and running on my local machine so I could test something out.

**Comment by ronkorving** [comment]
I've used this module (`memcached`) successfully to connect to Couchbase in the past, but it's been ages tbh.

**Comment by kbjr** [comment]
Yeah, I've seen other mentions in the issues about other people who have used it, but I don't see any examples at all about how to configure it (and clearly based on the errors I'm getting, something's not set up right).

**Comment by renedx** [comment]
In the basics it should work, but for me the last time using it is a while ago too. The only thing I can think of and that seems to match with the error message is authentication. Did you enable authentication on the bucket? Because you cannot do that on membase buckets.
