### ISSUE TITLE
true binary payloads?

### ISSUE THREAD

**Issue by iakoder** [3rd-Eden/memcached#308]
Is it possible to read and write a binary payload using this library without it being converted?  Although the hotchicks.jpg unit test passes it doesn't test to see that the data passed to the memcached server is actually the same as the contents of the file.  It's not.  The contents of the file are encoded so that although the .jpg file is 101,947 bytes the entry in the memcached server is 153,327 bytes.

If this module doesn't support binary payloads does anyone know of one that does?

**Comment by 3rd-Eden** [comment]
It's using a text based protocol. This library doesn't support the binary protocol.

**Comment by iakoder** [comment]
I'm not talking about the protocol.  I'm talking about the payload.  Why doesn't this library store a .jpg without mangling it?
