### ISSUE TITLE
return result from memcached.get

### ISSUE THREAD

**Issue by ssdk86** [3rd-Eden/memcached#350]
Hello!

It is possible to return value from memcached get method?
```
memcached.set('foo', 'bar', 10, function (err) { });

memcached.get('foo', function (err, data) {
    console.log(data); // bar
});

let data = memcached.get('foo', function (err, data) {
    return data;
});

console.log(data); // undefined
```

**Comment by acarrasco** [comment]
The I/O model of node.js is asynchronous, so returning plain values is not a viable option.

What could be done is to return _promises_, and then take advantage of ES6 `await` to extract the value in the current execution context.

I am not sure if promisifying the API is in the roadmap though, but you could use this wrapper library https://www.npmjs.com/package/memcached-promisify

**Comment by ssdk86** [comment]
thsnks, acarrasco! it's work with  https://www.npmjs.com/package/memcached-promisify!
